public final class android.system.ErrnoException extends java.lang.Exception
{
    private final java.lang.String functionName;
    public final int errno;

    public void <init>(java.lang.String, int)
    {
        android.system.ErrnoException this;
        java.lang.String functionName;
        int errno;

        this := @this: android.system.ErrnoException;

        functionName := @parameter0: java.lang.String;

        errno := @parameter1: int;

        specialinvoke this.<java.lang.Exception: void <init>()>();

        this.<android.system.ErrnoException: java.lang.String functionName> = functionName;

        this.<android.system.ErrnoException: int errno> = errno;

        return;
    }

    public void <init>(java.lang.String, int, java.lang.Throwable)
    {
        android.system.ErrnoException this;
        java.lang.String functionName;
        int errno;
        java.lang.Throwable cause;

        this := @this: android.system.ErrnoException;

        functionName := @parameter0: java.lang.String;

        errno := @parameter1: int;

        cause := @parameter2: java.lang.Throwable;

        specialinvoke this.<java.lang.Exception: void <init>(java.lang.Throwable)>(cause);

        this.<android.system.ErrnoException: java.lang.String functionName> = functionName;

        this.<android.system.ErrnoException: int errno> = errno;

        return;
    }

    public java.lang.String getMessage()
    {
        android.system.ErrnoException this;
        java.lang.String description, $r2, $r10, errnoName#1;
        int $i0, $i1, $i2;
        libcore.io.Os $r0;
        java.lang.StringBuilder $r1, $r3, $r4, $r5, $r6, $r7, $r8, $r9, $r11, $r12;

        this := @this: android.system.ErrnoException;

        $i0 = this.<android.system.ErrnoException: int errno>;

        errnoName#1 = staticinvoke <android.system.OsConstants: java.lang.String errnoName(int)>($i0);

        if errnoName#1 != null goto label1;

        $r9 = new java.lang.StringBuilder;

        specialinvoke $r9.<java.lang.StringBuilder: void <init>()>();

        $r11 = virtualinvoke $r9.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>("errno ");

        $i2 = this.<android.system.ErrnoException: int errno>;

        $r12 = virtualinvoke $r11.<java.lang.StringBuilder: java.lang.StringBuilder append(int)>($i2);

        errnoName#1 = virtualinvoke $r12.<java.lang.StringBuilder: java.lang.String toString()>();

     label1:
        $r0 = <libcore.io.Libcore: libcore.io.Os os>;

        $i1 = this.<android.system.ErrnoException: int errno>;

        description = interfaceinvoke $r0.<libcore.io.Os: java.lang.String strerror(int)>($i1);

        $r1 = new java.lang.StringBuilder;

        specialinvoke $r1.<java.lang.StringBuilder: void <init>()>();

        $r2 = this.<android.system.ErrnoException: java.lang.String functionName>;

        $r3 = virtualinvoke $r1.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>($r2);

        $r4 = virtualinvoke $r3.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(" failed: ");

        $r5 = virtualinvoke $r4.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(errnoName#1);

        $r6 = virtualinvoke $r5.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(" (");

        $r7 = virtualinvoke $r6.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(description);

        $r8 = virtualinvoke $r7.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(")");

        $r10 = virtualinvoke $r8.<java.lang.StringBuilder: java.lang.String toString()>();

        return $r10;
    }

    public java.io.IOException rethrowAsIOException() throws java.io.IOException
    {
        android.system.ErrnoException this;
        java.io.IOException newException, $r0;
        java.lang.String $r1;

        this := @this: android.system.ErrnoException;

        $r0 = new java.io.IOException;

        $r1 = virtualinvoke this.<android.system.ErrnoException: java.lang.String getMessage()>();

        specialinvoke $r0.<java.io.IOException: void <init>(java.lang.String)>($r1);

        newException = $r0;

        virtualinvoke newException.<java.io.IOException: java.lang.Throwable initCause(java.lang.Throwable)>(this);

        throw newException;
    }

    public java.net.SocketException rethrowAsSocketException() throws java.net.SocketException
    {
        android.system.ErrnoException this;
        java.net.SocketException $r0;
        java.lang.String $r1;

        this := @this: android.system.ErrnoException;

        $r0 = new java.net.SocketException;

        $r1 = virtualinvoke this.<android.system.ErrnoException: java.lang.String getMessage()>();

        specialinvoke $r0.<java.net.SocketException: void <init>(java.lang.String,java.lang.Throwable)>($r1, this);

        throw $r0;
    }
}
